name: CI for Maven Java

on: workflow_dispatch

jobs:
 build:
 runs-on: ubuntu-latest
 steps:

   - name: checkout
   uses: actions/checkout@4.2.2
   - name: Setup Java JDK
   uses: actions/setup-java@v5.0.0
   with:
    java-version: 5
    distribution: microsoft

 
